### PR TITLE
Improvements for FoamFix

### PR DESCRIPTION
**Pull request by CDAGaming**
Changes:
 - IDE Code Cleanup (IntelliJ Idea, might readd the Throw Exceptions if they end up causing issues)
 - Updated to a New MCP Snapshot and Stabler Forge Version
 - Regression from 0.9.3, due to causing Crashes
 - .gitignore Added for Ignoring Files Generated by IDE or Build Processes/Workspace Setup
 - Replace Dangling JavaDoc Comments with Block Comments

ToDo:
 - Change 2017 to 2018 for Copyrights

### CODE REVIEW

**Comment by asiekierka** [comment]
Thank you, but I think I can handle the codebase as is. There are some commits in the pipeline on my hard disk, and the GitHub code is not meant for production usage while in dev.

**Comment by asiekierka** [comment]
I do appreciate the effort, however! Please ask next time, though. Just to avoid this kind of situation. If possible.

**Comment by CDAGaming** [comment]
Alright. Wasn't really sure how to contact you besides Github, but I will keep it in mind down the line once this is more stable :D

**Comment by asiekierka** [comment]
Open an issue, use e-mail or use IRC.

**Pull request closed without merging**
